### ISSUE TITLE
Stat script download error on minecraft 1.21 

### ISSUE THREAD

**Issue by Ka1nnn** [CommandLeo/scarpet#2]
So i wanted to install stat script on my 1.21 fabric server and i was following the instructions on "how to install" but it gives a completely different error message than what its supposed to

![2024-06-23_10 40 49](https://github.com/CommandLeo/scarpet/assets/136351694/29d20655-ea0f-4221-b13d-d30f63be8c2b)

it will still say it loads the script but the /stat command doesnt work at all, game doesnt even register it as a command like it doesnt exist.

**Comment by CommandLeo** [comment]
I have uploaded 1.21 display names to the repo, try downloading the script again.

**Comment by Ka1nnn** [comment]
works great now thanks again leo <3 closing the issue :)
